version: '3'
services:
  mongodb:
    container_name: tanks-mongo-db
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/dbn
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    volumes:
      - ./data/dbn:/data/dbn
    networks:
      - backend 
    command: mongod --logpath=/dev/null # --quiet
      
  tanks-battle:
    restart: always
    build: .
    image: tanks-battle-server
    expose:
      - "8080"
    ports:
      - 5000:5000
      - 9090:8080
    networks:
      - backend
    depends_on:
      - mongodb
      
      
networks:
  backend: 